// Generated from https://api.quran.com/api/v4/chapters by scripts/gen-surahs.ts — do not edit by hand.
export type Surah = { id: number; nameEn: string; nameAr: string; meaning: string; verses: number; place: 'makkah' | 'madinah' };

export const SURAHS: Surah[] = [
  {"id": 1, "nameEn": "Al-Fatihah", "nameAr": "الفاتحة", "meaning": "The Opener", "verses": 7, "place": "makkah"},
  {"id": 2, "nameEn": "Al-Baqarah", "nameAr": "البقرة", "meaning": "The Cow", "verses": 286, "place": "madinah"},
  {"id": 3, "nameEn": "Ali 'Imran", "nameAr": "آل عمران", "meaning": "Family of Imran", "verses": 200, "place": "madinah"},
  {"id": 4, "nameEn": "An-Nisa", "nameAr": "النساء", "meaning": "The Women", "verses": 176, "place": "madinah"},
  {"id": 5, "nameEn": "Al-Ma'idah", "nameAr": "المائدة", "meaning": "The Table Spread", "verses": 120, "place": "madinah"},
  {"id": 6, "nameEn": "Al-An'am", "nameAr": "الأنعام", "meaning": "The Cattle", "verses": 165, "place": "makkah"},
  {"id": 7, "nameEn": "Al-A'raf", "nameAr": "الأعراف", "meaning": "The Heights", "verses": 206, "place": "makkah"},
  {"id": 8, "nameEn": "Al-Anfal", "nameAr": "الأنفال", "meaning": "The Spoils of War", "verses": 75, "place": "madinah"},
  {"id": 9, "nameEn": "At-Tawbah", "nameAr": "التوبة", "meaning": "The Repentance", "verses": 129, "place": "madinah"},
  {"id": 10, "nameEn": "Yunus", "nameAr": "يونس", "meaning": "Jonah", "verses": 109, "place": "makkah"},
  {"id": 11, "nameEn": "Hud", "nameAr": "هود", "meaning": "Hud", "verses": 123, "place": "makkah"},
  {"id": 12, "nameEn": "Yusuf", "nameAr": "يوسف", "meaning": "Joseph", "verses": 111, "place": "makkah"},
  {"id": 13, "nameEn": "Ar-Ra'd", "nameAr": "الرعد", "meaning": "The Thunder", "verses": 43, "place": "madinah"},
  {"id": 14, "nameEn": "Ibrahim", "nameAr": "ابراهيم", "meaning": "Abraham", "verses": 52, "place": "makkah"},
  {"id": 15, "nameEn": "Al-Hijr", "nameAr": "الحجر", "meaning": "The Rocky Tract", "verses": 99, "place": "makkah"},
  {"id": 16, "nameEn": "An-Nahl", "nameAr": "النحل", "meaning": "The Bee", "verses": 128, "place": "makkah"},
  {"id": 17, "nameEn": "Al-Isra", "nameAr": "الإسراء", "meaning": "The Night Journey", "verses": 111, "place": "makkah"},
  {"id": 18, "nameEn": "Al-Kahf", "nameAr": "الكهف", "meaning": "The Cave", "verses": 110, "place": "makkah"},
  {"id": 19, "nameEn": "Maryam", "nameAr": "مريم", "meaning": "Mary", "verses": 98, "place": "makkah"},
  {"id": 20, "nameEn": "Taha", "nameAr": "طه", "meaning": "Ta-Ha", "verses": 135, "place": "makkah"},
  {"id": 21, "nameEn": "Al-Anbya", "nameAr": "الأنبياء", "meaning": "The Prophets", "verses": 112, "place": "makkah"},
  {"id": 22, "nameEn": "Al-Hajj", "nameAr": "الحج", "meaning": "The Pilgrimage", "verses": 78, "place": "madinah"},
  {"id": 23, "nameEn": "Al-Mu'minun", "nameAr": "المؤمنون", "meaning": "The Believers", "verses": 118, "place": "makkah"},
  {"id": 24, "nameEn": "An-Nur", "nameAr": "النور", "meaning": "The Light", "verses": 64, "place": "madinah"},
  {"id": 25, "nameEn": "Al-Furqan", "nameAr": "الفرقان", "meaning": "The Criterion", "verses": 77, "place": "makkah"},
  {"id": 26, "nameEn": "Ash-Shu'ara", "nameAr": "الشعراء", "meaning": "The Poets", "verses": 227, "place": "makkah"},
  {"id": 27, "nameEn": "An-Naml", "nameAr": "النمل", "meaning": "The Ant", "verses": 93, "place": "makkah"},
  {"id": 28, "nameEn": "Al-Qasas", "nameAr": "القصص", "meaning": "The Stories", "verses": 88, "place": "makkah"},
  {"id": 29, "nameEn": "Al-'Ankabut", "nameAr": "العنكبوت", "meaning": "The Spider", "verses": 69, "place": "makkah"},
  {"id": 30, "nameEn": "Ar-Rum", "nameAr": "الروم", "meaning": "The Romans", "verses": 60, "place": "makkah"},
  {"id": 31, "nameEn": "Luqman", "nameAr": "لقمان", "meaning": "Luqman", "verses": 34, "place": "makkah"},
  {"id": 32, "nameEn": "As-Sajdah", "nameAr": "السجدة", "meaning": "The Prostration", "verses": 30, "place": "makkah"},
  {"id": 33, "nameEn": "Al-Ahzab", "nameAr": "الأحزاب", "meaning": "The Combined Forces", "verses": 73, "place": "madinah"},
  {"id": 34, "nameEn": "Saba", "nameAr": "سبإ", "meaning": "Sheba", "verses": 54, "place": "makkah"},
  {"id": 35, "nameEn": "Fatir", "nameAr": "فاطر", "meaning": "Originator", "verses": 45, "place": "makkah"},
  {"id": 36, "nameEn": "Ya-Sin", "nameAr": "يس", "meaning": "Ya Sin", "verses": 83, "place": "makkah"},
  {"id": 37, "nameEn": "As-Saffat", "nameAr": "الصافات", "meaning": "Those who set the Ranks", "verses": 182, "place": "makkah"},
  {"id": 38, "nameEn": "Sad", "nameAr": "ص", "meaning": "The Letter \"Saad\"", "verses": 88, "place": "makkah"},
  {"id": 39, "nameEn": "Az-Zumar", "nameAr": "الزمر", "meaning": "The Troops", "verses": 75, "place": "makkah"},
  {"id": 40, "nameEn": "Ghafir", "nameAr": "غافر", "meaning": "The Forgiver", "verses": 85, "place": "makkah"},
  {"id": 41, "nameEn": "Fussilat", "nameAr": "فصلت", "meaning": "Explained in Detail", "verses": 54, "place": "makkah"},
  {"id": 42, "nameEn": "Ash-Shuraa", "nameAr": "الشورى", "meaning": "The Consultation", "verses": 53, "place": "makkah"},
  {"id": 43, "nameEn": "Az-Zukhruf", "nameAr": "الزخرف", "meaning": "The Ornaments of Gold", "verses": 89, "place": "makkah"},
  {"id": 44, "nameEn": "Ad-Dukhan", "nameAr": "الدخان", "meaning": "The Smoke", "verses": 59, "place": "makkah"},
  {"id": 45, "nameEn": "Al-Jathiyah", "nameAr": "الجاثية", "meaning": "The Crouching", "verses": 37, "place": "makkah"},
  {"id": 46, "nameEn": "Al-Ahqaf", "nameAr": "الأحقاف", "meaning": "The Wind-Curved Sandhills", "verses": 35, "place": "makkah"},
  {"id": 47, "nameEn": "Muhammad", "nameAr": "محمد", "meaning": "Muhammad", "verses": 38, "place": "madinah"},
  {"id": 48, "nameEn": "Al-Fath", "nameAr": "الفتح", "meaning": "The Victory", "verses": 29, "place": "madinah"},
  {"id": 49, "nameEn": "Al-Hujurat", "nameAr": "الحجرات", "meaning": "The Rooms", "verses": 18, "place": "madinah"},
  {"id": 50, "nameEn": "Qaf", "nameAr": "ق", "meaning": "The Letter \"Qaf\"", "verses": 45, "place": "makkah"},
  {"id": 51, "nameEn": "Adh-Dhariyat", "nameAr": "الذاريات", "meaning": "The Winnowing Winds", "verses": 60, "place": "makkah"},
  {"id": 52, "nameEn": "At-Tur", "nameAr": "الطور", "meaning": "The Mount", "verses": 49, "place": "makkah"},
  {"id": 53, "nameEn": "An-Najm", "nameAr": "النجم", "meaning": "The Star", "verses": 62, "place": "makkah"},
  {"id": 54, "nameEn": "Al-Qamar", "nameAr": "القمر", "meaning": "The Moon", "verses": 55, "place": "makkah"},
  {"id": 55, "nameEn": "Ar-Rahman", "nameAr": "الرحمن", "meaning": "The Beneficent", "verses": 78, "place": "madinah"},
  {"id": 56, "nameEn": "Al-Waqi'ah", "nameAr": "الواقعة", "meaning": "The Inevitable", "verses": 96, "place": "makkah"},
  {"id": 57, "nameEn": "Al-Hadid", "nameAr": "الحديد", "meaning": "The Iron", "verses": 29, "place": "madinah"},
  {"id": 58, "nameEn": "Al-Mujadila", "nameAr": "المجادلة", "meaning": "The Pleading Woman", "verses": 22, "place": "madinah"},
  {"id": 59, "nameEn": "Al-Hashr", "nameAr": "الحشر", "meaning": "The Exile", "verses": 24, "place": "madinah"},
  {"id": 60, "nameEn": "Al-Mumtahanah", "nameAr": "الممتحنة", "meaning": "She that is to be examined", "verses": 13, "place": "madinah"},
  {"id": 61, "nameEn": "As-Saf", "nameAr": "الصف", "meaning": "The Ranks", "verses": 14, "place": "madinah"},
  {"id": 62, "nameEn": "Al-Jumu'ah", "nameAr": "الجمعة", "meaning": "The Congregation, Friday", "verses": 11, "place": "madinah"},
  {"id": 63, "nameEn": "Al-Munafiqun", "nameAr": "المنافقون", "meaning": "The Hypocrites", "verses": 11, "place": "madinah"},
  {"id": 64, "nameEn": "At-Taghabun", "nameAr": "التغابن", "meaning": "The Mutual Disillusion", "verses": 18, "place": "madinah"},
  {"id": 65, "nameEn": "At-Talaq", "nameAr": "الطلاق", "meaning": "The Divorce", "verses": 12, "place": "madinah"},
  {"id": 66, "nameEn": "At-Tahrim", "nameAr": "التحريم", "meaning": "The Prohibition", "verses": 12, "place": "madinah"},
  {"id": 67, "nameEn": "Al-Mulk", "nameAr": "الملك", "meaning": "The Sovereignty", "verses": 30, "place": "makkah"},
  {"id": 68, "nameEn": "Al-Qalam", "nameAr": "القلم", "meaning": "The Pen", "verses": 52, "place": "makkah"},
  {"id": 69, "nameEn": "Al-Haqqah", "nameAr": "الحاقة", "meaning": "The Reality", "verses": 52, "place": "makkah"},
  {"id": 70, "nameEn": "Al-Ma'arij", "nameAr": "المعارج", "meaning": "The Ascending Stairways", "verses": 44, "place": "makkah"},
  {"id": 71, "nameEn": "Nuh", "nameAr": "نوح", "meaning": "Noah", "verses": 28, "place": "makkah"},
  {"id": 72, "nameEn": "Al-Jinn", "nameAr": "الجن", "meaning": "The Jinn", "verses": 28, "place": "makkah"},
  {"id": 73, "nameEn": "Al-Muzzammil", "nameAr": "المزمل", "meaning": "The Enshrouded One", "verses": 20, "place": "makkah"},
  {"id": 74, "nameEn": "Al-Muddaththir", "nameAr": "المدثر", "meaning": "The Cloaked One", "verses": 56, "place": "makkah"},
  {"id": 75, "nameEn": "Al-Qiyamah", "nameAr": "القيامة", "meaning": "The Resurrection", "verses": 40, "place": "makkah"},
  {"id": 76, "nameEn": "Al-Insan", "nameAr": "الانسان", "meaning": "The Man", "verses": 31, "place": "madinah"},
  {"id": 77, "nameEn": "Al-Mursalat", "nameAr": "المرسلات", "meaning": "The Emissaries", "verses": 50, "place": "makkah"},
  {"id": 78, "nameEn": "An-Naba", "nameAr": "النبإ", "meaning": "The Tidings", "verses": 40, "place": "makkah"},
  {"id": 79, "nameEn": "An-Nazi'at", "nameAr": "النازعات", "meaning": "Those who drag forth", "verses": 46, "place": "makkah"},
  {"id": 80, "nameEn": "'Abasa", "nameAr": "عبس", "meaning": "He Frowned", "verses": 42, "place": "makkah"},
  {"id": 81, "nameEn": "At-Takwir", "nameAr": "التكوير", "meaning": "The Overthrowing", "verses": 29, "place": "makkah"},
  {"id": 82, "nameEn": "Al-Infitar", "nameAr": "الإنفطار", "meaning": "The Cleaving", "verses": 19, "place": "makkah"},
  {"id": 83, "nameEn": "Al-Mutaffifin", "nameAr": "المطففين", "meaning": "The Defrauding", "verses": 36, "place": "makkah"},
  {"id": 84, "nameEn": "Al-Inshiqaq", "nameAr": "الإنشقاق", "meaning": "The Sundering", "verses": 25, "place": "makkah"},
  {"id": 85, "nameEn": "Al-Buruj", "nameAr": "البروج", "meaning": "The Mansions of the Stars", "verses": 22, "place": "makkah"},
  {"id": 86, "nameEn": "At-Tariq", "nameAr": "الطارق", "meaning": "The Nightcommer", "verses": 17, "place": "makkah"},
  {"id": 87, "nameEn": "Al-A'la", "nameAr": "الأعلى", "meaning": "The Most High", "verses": 19, "place": "makkah"},
  {"id": 88, "nameEn": "Al-Ghashiyah", "nameAr": "الغاشية", "meaning": "The Overwhelming", "verses": 26, "place": "makkah"},
  {"id": 89, "nameEn": "Al-Fajr", "nameAr": "الفجر", "meaning": "The Dawn", "verses": 30, "place": "makkah"},
  {"id": 90, "nameEn": "Al-Balad", "nameAr": "البلد", "meaning": "The City", "verses": 20, "place": "makkah"},
  {"id": 91, "nameEn": "Ash-Shams", "nameAr": "الشمس", "meaning": "The Sun", "verses": 15, "place": "makkah"},
  {"id": 92, "nameEn": "Al-Layl", "nameAr": "الليل", "meaning": "The Night", "verses": 21, "place": "makkah"},
  {"id": 93, "nameEn": "Ad-Duhaa", "nameAr": "الضحى", "meaning": "The Morning Hours", "verses": 11, "place": "makkah"},
  {"id": 94, "nameEn": "Ash-Sharh", "nameAr": "الشرح", "meaning": "The Relief", "verses": 8, "place": "makkah"},
  {"id": 95, "nameEn": "At-Tin", "nameAr": "التين", "meaning": "The Fig", "verses": 8, "place": "makkah"},
  {"id": 96, "nameEn": "Al-'Alaq", "nameAr": "العلق", "meaning": "The Clot", "verses": 19, "place": "makkah"},
  {"id": 97, "nameEn": "Al-Qadr", "nameAr": "القدر", "meaning": "The Power", "verses": 5, "place": "makkah"},
  {"id": 98, "nameEn": "Al-Bayyinah", "nameAr": "البينة", "meaning": "The Clear Proof", "verses": 8, "place": "madinah"},
  {"id": 99, "nameEn": "Az-Zalzalah", "nameAr": "الزلزلة", "meaning": "The Earthquake", "verses": 8, "place": "madinah"},
  {"id": 100, "nameEn": "Al-'Adiyat", "nameAr": "العاديات", "meaning": "The Courser", "verses": 11, "place": "makkah"},
  {"id": 101, "nameEn": "Al-Qari'ah", "nameAr": "القارعة", "meaning": "The Calamity", "verses": 11, "place": "makkah"},
  {"id": 102, "nameEn": "At-Takathur", "nameAr": "التكاثر", "meaning": "The Rivalry in world increase", "verses": 8, "place": "makkah"},
  {"id": 103, "nameEn": "Al-'Asr", "nameAr": "العصر", "meaning": "The Declining Day", "verses": 3, "place": "makkah"},
  {"id": 104, "nameEn": "Al-Humazah", "nameAr": "الهمزة", "meaning": "The Traducer", "verses": 9, "place": "makkah"},
  {"id": 105, "nameEn": "Al-Fil", "nameAr": "الفيل", "meaning": "The Elephant", "verses": 5, "place": "makkah"},
  {"id": 106, "nameEn": "Quraysh", "nameAr": "قريش", "meaning": "Quraysh", "verses": 4, "place": "makkah"},
  {"id": 107, "nameEn": "Al-Ma'un", "nameAr": "الماعون", "meaning": "The Small kindnesses", "verses": 7, "place": "makkah"},
  {"id": 108, "nameEn": "Al-Kawthar", "nameAr": "الكوثر", "meaning": "The Abundance", "verses": 3, "place": "makkah"},
  {"id": 109, "nameEn": "Al-Kafirun", "nameAr": "الكافرون", "meaning": "The Disbelievers", "verses": 6, "place": "makkah"},
  {"id": 110, "nameEn": "An-Nasr", "nameAr": "النصر", "meaning": "The Divine Support", "verses": 3, "place": "madinah"},
  {"id": 111, "nameEn": "Al-Masad", "nameAr": "المسد", "meaning": "The Palm Fiber", "verses": 5, "place": "makkah"},
  {"id": 112, "nameEn": "Al-Ikhlas", "nameAr": "الإخلاص", "meaning": "The Sincerity", "verses": 4, "place": "makkah"},
  {"id": 113, "nameEn": "Al-Falaq", "nameAr": "الفلق", "meaning": "The Daybreak", "verses": 5, "place": "makkah"},
  {"id": 114, "nameEn": "An-Nas", "nameAr": "الناس", "meaning": "Mankind", "verses": 6, "place": "makkah"},
];

export function getSurah(id: number): Surah | undefined {
  return SURAHS[id - 1];
}
